### ISSUE TITLE
`Safe\date` function is missing

### ISSUE THREAD

**Issue by the-csaba** [shish/safe#21]
After switching to this fork, the `Safe\date` function is missing.

PHPStan also reports it: "Used function Safe\date not found."

According to the official doco (https://www.php.net/manual/en/function.date.php), it looks like it would still be a good idea to have it.

> Errors/Exceptions[ ¶](https://www.php.net/manual/en/function.date.php#refsect1-function.date-errors)
>
> Every call to a date/time function will generate a [E_WARNING](https://www.php.net/manual/en/errorfunc.constants.php#constant.e-warning) if the time zone is not valid. See also [date_default_timezone_set()](https://www.php.net/manual/en/function.date-default-timezone-set.php)

**Comment by shish** [comment]
It looks like `Safe\date` never actually handled that case -

- PHP7 returns `false` for non-integer `$timestamp`
- `thecodingmachine/safe` turns "function which returns false on error" into "function which raises an Exception on error"
- PHP8 raises an exception for non-integer `$timestamp`

So as of PHP8, it is safe (according to the definitions of this project) to use `date` directly

For reference, the old Safe\date - https://github.com/thecodingmachine/safe/blob/3a6e43b4be3d3d65b272c2660300a50658ce168b/generated/datetime.php#L446-L475
