### ISSUE TITLE
generated openssl functions are broken

### ISSUE THREAD

**Issue by smoench** [shish/safe#35]
As an example [`openssl_cipher_key_length`](https://github.com/shish/safe/blob/master/generated/openssl.php#L34) return type is marked as void but should return an integer.

```php
/**
 * Gets the cipher key length.
 *
 * @param string $cipher_algo The cipher method, see openssl_get_cipher_methods for a list of potential values.
 * @return  Returns the cipher length on success.
 * @throws OpensslException
 *
 */
function openssl_cipher_key_length(string $cipher_algo): void
{
    error_clear_last();
    $safeResult = \openssl_cipher_key_length($cipher_algo);
    if ($safeResult === false) {
        throw OpensslException::createFromPhpError();
    }
}
```
There several more openssl functions with the same issue.

**Comment by smoench** [comment]
Solution can be merged from origin -> https://github.com/thecodingmachine/safe/pull/506

**Comment by smoench** [comment]
@shish Might it be possible to pull my changes ☝️ in this repository and make a new release? So we are able to update to the latest version of infection -> https://github.com/infection/infection/pull/2017. Thanks in advance :-)

**Comment by shish** [comment]
it's a bit messy, but I've manually backported that, regenerated, and tagged v2.6.4 -- does that work?

**Comment by smoench** [comment]
Unfortunately no, because the tag is not synced to packagist -> https://packagist.org/packages/shish/safe

**Comment by shish** [comment]
Weird, it always did that automatically and pretty much instantly before o_O

I've manually clicked the "update" button in packagist and it appeared now

**Comment by smoench** [comment]
Thanks it worked :-)
